#!/bin/bash

commit=$(git rev-parse HEAD)

version=$(git tag --contains "$commit")
if [ $? -ne 0 ]; then
    version="untagged"
fi
if [ -z "$version" ]; then
    version="untagged"
fi

when=$(git log -1 | grep Date | sed 's/Date: *//')


cat <<EOF > vars.go
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// $(date -u --rfc-3339=seconds -u)
// using data from
// 'git describe' && 'git log' commands output
package version

var (
    Handler = versionHandler{
        Version: "$version",
        Commit:  "$commit",
        When:    "$when",
    }
)

EOF
