#!/bin/bash

version=$(git describe)
if [ $? -ne 0 ]; then
    version="untagged"
fi

commit=$(git log --pretty=oneline -1 | cut -d ' ' -f 1)
when=$(git log -1 | grep Date | sed 's/Date: *//')



cat <<EOF > vars.go
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// $(date -u --rfc-3339=seconds -u)
// using data from
// 'git describe' && 'git log' commands output
package version


var (
	VERSION string = "$version"
    COMMIT  string = "$commit"
    WHEN    string = "$when"
)
EOF
